//This file is automatically generated, modifications will be lost!
typedef enum {
    //8-bit
    //R8
    CCColourFormatR8Unorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 8, CCColourFormatChannelOffset0),
    CCColourFormatR8Unorm_sRGB  = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 8, CCColourFormatChannelOffset0),
    CCColourFormatR8Snorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 8, CCColourFormatChannelOffset0),
    CCColourFormatR8Uint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 8, CCColourFormatChannelOffset0),
    CCColourFormatR8Sint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 8, CCColourFormatChannelOffset0),


    //G8
    CCColourFormatG8Unorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset0),
    CCColourFormatG8Unorm_sRGB  = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset0),
    CCColourFormatG8Snorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset0),
    CCColourFormatG8Uint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset0),
    CCColourFormatG8Sint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset0),


    //B8
    CCColourFormatB8Unorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 8, CCColourFormatChannelOffset0),
    CCColourFormatB8Unorm_sRGB  = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 8, CCColourFormatChannelOffset0),
    CCColourFormatB8Snorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 8, CCColourFormatChannelOffset0),
    CCColourFormatB8Uint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 8, CCColourFormatChannelOffset0),
    CCColourFormatB8Sint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 8, CCColourFormatChannelOffset0),


    //A8
    CCColourFormatA8Unorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0),
    CCColourFormatA8Snorm       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0),
    CCColourFormatA8Uint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0),
    CCColourFormatA8Sint        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0),


    //16-bit
    //R16
    CCColourFormatR16Unorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 16, CCColourFormatChannelOffset0),
    CCColourFormatR16Snorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 16, CCColourFormatChannelOffset0),
    CCColourFormatR16Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 16, CCColourFormatChannelOffset0),
    CCColourFormatR16Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 16, CCColourFormatChannelOffset0),
    CCColourFormatR16Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 16, CCColourFormatChannelOffset0),


    //G16
    CCColourFormatG16Unorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset0),
    CCColourFormatG16Snorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset0),
    CCColourFormatG16Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset0),
    CCColourFormatG16Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset0),
    CCColourFormatG16Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset0),


    //B16
    CCColourFormatB16Unorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 16, CCColourFormatChannelOffset0),
    CCColourFormatB16Snorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 16, CCColourFormatChannelOffset0),
    CCColourFormatB16Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 16, CCColourFormatChannelOffset0),
    CCColourFormatB16Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 16, CCColourFormatChannelOffset0),
    CCColourFormatB16Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 16, CCColourFormatChannelOffset0),


    //A16
    CCColourFormatA16Unorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0),
    CCColourFormatA16Snorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0),
    CCColourFormatA16Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0),
    CCColourFormatA16Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0),
    CCColourFormatA16Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0),


    //RG8
    CCColourFormatRG8Unorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1),
    CCColourFormatRG8Unorm_sRGB = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1),
    CCColourFormatRG8Snorm      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1),
    CCColourFormatRG8Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1),
    CCColourFormatRG8Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1),


    //R5G6B5
    CCColourFormatR5G6B5Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2),
    CCColourFormatR5G6B5Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2),
    CCColourFormatR5G6B5Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2),
    CCColourFormatR5G6B5Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2),


    //B5G6R5
    CCColourFormatB5G6R5Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2),
    CCColourFormatB5G6R5Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2),
    CCColourFormatB5G6R5Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2),
    CCColourFormatB5G6R5Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 6, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2),


    //RGB5A1
    CCColourFormatRGB5A1Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),
    CCColourFormatRGB5A1Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),
    CCColourFormatRGB5A1Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),
    CCColourFormatRGB5A1Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),


    //BGR5A1
    CCColourFormatBGR5A1Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),
    CCColourFormatBGR5A1Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),
    CCColourFormatBGR5A1Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),
    CCColourFormatBGR5A1Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset3),


    //A1RGB5
    CCColourFormatA1RGB5Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset3),
    CCColourFormatA1RGB5Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset3),
    CCColourFormatA1RGB5Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset3),
    CCColourFormatA1RGB5Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset3),


    //A1BGR5
    CCColourFormatA1BGR5Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset3),
    CCColourFormatA1BGR5Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset3),
    CCColourFormatA1BGR5Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset3),
    CCColourFormatA1BGR5Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 1, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  5, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 5, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   5, CCColourFormatChannelOffset3),


    //RGBA4
    CCColourFormatRGBA4Unorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),
    CCColourFormatRGBA4Snorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),
    CCColourFormatRGBA4Uint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),
    CCColourFormatRGBA4Sint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),


    //BGRA4
    CCColourFormatBGRA4Unorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),
    CCColourFormatBGRA4Snorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),
    CCColourFormatBGRA4Uint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),
    CCColourFormatBGRA4Sint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset3),


    //ARGB4
    CCColourFormatARGB4Unorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset3),
    CCColourFormatARGB4Snorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset3),
    CCColourFormatARGB4Uint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset3),
    CCColourFormatARGB4Sint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset3),


    //ABGR4
    CCColourFormatABGR4Unorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset3),
    CCColourFormatABGR4Snorm    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset3),
    CCColourFormatABGR4Uint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset3),
    CCColourFormatABGR4Sint     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 4, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  4, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 4, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   4, CCColourFormatChannelOffset3),


    //24-bit
    //RGB8
    CCColourFormatRGB8Unorm     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2),
    CCColourFormatRGB8Unorm_sRGB        = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                            | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                            | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                            | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2),
    CCColourFormatRGB8Snorm     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2),
    CCColourFormatRGB8Uint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2),
    CCColourFormatRGB8Sint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2),


    //BGR8
    CCColourFormatBGR8Unorm     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2),
    CCColourFormatBGR8Unorm_sRGB        = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                            | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                            | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                            | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2),
    CCColourFormatBGR8Snorm     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2),
    CCColourFormatBGR8Uint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2),
    CCColourFormatBGR8Sint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2),


    //32-bit
    //R32
    CCColourFormatR32Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 32, CCColourFormatChannelOffset0),
    CCColourFormatR32Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 32, CCColourFormatChannelOffset0),
    CCColourFormatR32Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed, 32, CCColourFormatChannelOffset0),


    //G32
    CCColourFormatG32Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset0),
    CCColourFormatG32Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset0),
    CCColourFormatG32Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset0),


    //B32
    CCColourFormatB32Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 32, CCColourFormatChannelOffset0),
    CCColourFormatB32Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 32, CCColourFormatChannelOffset0),
    CCColourFormatB32Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue, 32, CCColourFormatChannelOffset0),


    //A32
    CCColourFormatA32Uint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0),
    CCColourFormatA32Sint       = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0),
    CCColourFormatA32Float      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0),


    //RG16
    CCColourFormatRG16Unorm     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1),
    CCColourFormatRG16Snorm     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1),
    CCColourFormatRG16Uint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1),
    CCColourFormatRG16Sint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1),
    CCColourFormatRG16Float     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1),


    //RGBA8
    CCColourFormatRGBA8Unorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatRGBA8Unorm_sRGB   = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatRGBA8Snorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatRGBA8Uint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatRGBA8Sint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),


    //BGRA8
    CCColourFormatBGRA8Unorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatBGRA8Unorm_sRGB   = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatBGRA8Snorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatBGRA8Uint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),
    CCColourFormatBGRA8Sint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset3),


    //ARGB8
    CCColourFormatARGB8Unorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset3),
    CCColourFormatARGB8Unorm_sRGB   = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset3),
    CCColourFormatARGB8Snorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset3),
    CCColourFormatARGB8Uint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset3),
    CCColourFormatARGB8Sint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset3),


    //ABGR8
    CCColourFormatABGR8Unorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset3),
    CCColourFormatABGR8Unorm_sRGB   = CCColourFormatSpaceRGB_sRGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset3),
    CCColourFormatABGR8Snorm        = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset3),
    CCColourFormatABGR8Uint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset3),
    CCColourFormatABGR8Sint         = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 8, CCColourFormatChannelOffset0)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  8, CCColourFormatChannelOffset1)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 8, CCColourFormatChannelOffset2)
                                        | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   8, CCColourFormatChannelOffset3),


    //64-bit
    //RG32
    CCColourFormatRG32Uint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1),
    CCColourFormatRG32Sint      = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1),
    CCColourFormatRG32Float     = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1),


    //RGBA16
    CCColourFormatRGBA16Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatRGBA16Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatRGBA16Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatRGBA16Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatRGBA16Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),


    //BGRA16
    CCColourFormatBGRA16Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatBGRA16Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatBGRA16Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatBGRA16Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),
    CCColourFormatBGRA16Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset3),


    //ARGB16
    CCColourFormatARGB16Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset3),
    CCColourFormatARGB16Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset3),
    CCColourFormatARGB16Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset3),
    CCColourFormatARGB16Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset3),
    CCColourFormatARGB16Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset3),


    //ABGR16
    CCColourFormatABGR16Unorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset3),
    CCColourFormatABGR16Snorm   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger | CCColourFormatNormalized
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset3),
    CCColourFormatABGR16Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset3),
    CCColourFormatABGR16Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset3),
    CCColourFormatABGR16Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 16, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  16, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 16, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   16, CCColourFormatChannelOffset3),


    //128-bit
    //RGBA32
    CCColourFormatRGBA32Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset3),
    CCColourFormatRGBA32Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset3),
    CCColourFormatRGBA32Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset3),


    //BGRA32
    CCColourFormatBGRA32Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset3),
    CCColourFormatBGRA32Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset3),
    CCColourFormatBGRA32Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset3),


    //ARGB32
    CCColourFormatARGB32Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset3),
    CCColourFormatARGB32Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset3),
    CCColourFormatARGB32Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset3),


    //ABGR32
    CCColourFormatABGR32Uint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset3),
    CCColourFormatABGR32Sint    = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset3),
    CCColourFormatABGR32Float   = CCColourFormatSpaceRGB_RGB | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha, 32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelBlue,  32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelGreen, 32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelRed,   32, CCColourFormatChannelOffset3),
} CCColourFormatRGB;
