//This file is automatically generated, modifications will be lost!
typedef enum {
    //96-bit
    //HSV32
    CCColourFormatHSV32Uint     = CCColourFormatSpaceHS_HSV | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelHue,        32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelSaturation, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelValue,      32, CCColourFormatChannelOffset2),
    CCColourFormatHSV32Sint     = CCColourFormatSpaceHS_HSV | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelHue,        32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelSaturation, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelValue,      32, CCColourFormatChannelOffset2),
    CCColourFormatHSV32Float    = CCColourFormatSpaceHS_HSV | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelHue,        32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelSaturation, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelValue,      32, CCColourFormatChannelOffset2),


    //128-bit
    //HSVA32
    CCColourFormatHSVA32Uint    = CCColourFormatSpaceHS_HSV | CCColourFormatTypeUnsignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelHue,        32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelSaturation, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelValue,      32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha,      32, CCColourFormatChannelOffset3),
    CCColourFormatHSVA32Sint    = CCColourFormatSpaceHS_HSV | CCColourFormatTypeSignedInteger
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelHue,        32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelSaturation, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelValue,      32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha,      32, CCColourFormatChannelOffset3),
    CCColourFormatHSVA32Float   = CCColourFormatSpaceHS_HSV | CCColourFormatTypeFloat
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelHue,        32, CCColourFormatChannelOffset0)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelSaturation, 32, CCColourFormatChannelOffset1)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelValue,      32, CCColourFormatChannelOffset2)
                                    | CC_COLOUR_FORMAT_CHANNEL(CCColourFormatChannelAlpha,      32, CCColourFormatChannelOffset3),
} CCColourFormatHSV;
