file='src/ecs/ECSConfig.h'

echo '//This file is automatically generated, modifications will be lost!' > $file
echo '#ifndef CommonGameKit_ECSConfig_h' >> $file
echo '#define CommonGameKit_ECSConfig_h' >> $file
echo '' >> $file
echo '#include <CommonGameKit/Base.h>' >> $file
echo '' >> $file
ecs_tool config 20 >> $file
echo '#endif' >> $file
