#define ECS_MONITOR_COMPONENT (ECSComponentStorageTypePacked | ECSComponentStorageModifierDuplicate | ECSComponentStorageModifierDestructor | (ECS_MONITOR_COMPONENT_ID))
#define ECS_NAME_COMPONENT (ECSComponentStorageTypeIndexed | ECSComponentStorageModifierDestructor | (ECS_NAME_COMPONENT_ID))


#ifndef ECS_INDEXED_COMPONENT_ID_BASE
#define ECS_INDEXED_COMPONENT_ID_BASE 0
#endif

#ifndef ECS_MONITOR_COMPONENT_ID
#define ECS_MONITOR_COMPONENT_ID ECS_PACKED_COMPONENT_ID_BASE + ECS_MONITOR_COMPONENT_ID_RELATIVE
#endif

#ifndef ECS_MONITOR_COMPONENT_ID_RELATIVE
#define ECS_MONITOR_COMPONENT_ID_RELATIVE 0
#endif

#ifndef ECS_NAME_COMPONENT_ID
#define ECS_NAME_COMPONENT_ID ECS_INDEXED_COMPONENT_ID_BASE + ECS_NAME_COMPONENT_ID_RELATIVE
#endif

#ifndef ECS_NAME_COMPONENT_ID_RELATIVE
#define ECS_NAME_COMPONENT_ID_RELATIVE 0
#endif

#ifndef ECS_PACKED_COMPONENT_ID_BASE
#define ECS_PACKED_COMPONENT_ID_BASE 0
#endif

