#define ECS_MONITOR_COMPONENT (ECSComponentStorageTypePacked | ECSComponentStorageModifierDuplicate | ECSComponentStorageModifierDestructor | (ECS_MONITOR_COMPONENT_ID))

#ifndef ECS_COMPONENT_ID_BASE
#define ECS_COMPONENT_ID_BASE 0
#endif

#ifndef ECS_MONITOR_COMPONENT_ID_RELATIVE
#define ECS_MONITOR_COMPONENT_ID_RELATIVE 0
#endif

#ifndef ECS_MONITOR_COMPONENT_ID
#define ECS_MONITOR_COMPONENT_ID (ECS_COMPONENT_ID_BASE + ECS_MONITOR_COMPONENT_ID_RELATIVE)
#endif
