//This file is automatically generated, modifications will be lost!
#include "ExpressionSetup.h"
#include "ExpressionEvaluator.h"

#include "IOExpressions.h"
#include "MathExpressions.h"
#include "ProjectExpressions.h"

void CCExpressionSetup(void)
{
    CCExpressionEvaluatorRegister("print", CCIOExpressionPrint);
    CCExpressionEvaluatorRegister("+", CCMathExpressionAddition);
    CCExpressionEvaluatorRegister("-", CCMathExpressionSubtract);
    CCExpressionEvaluatorRegister("*", CCMathExpressionMultiply);
    CCExpressionEvaluatorRegister("/", CCMathExpressionDivide);
    CCExpressionEvaluatorRegister("min", CCMathExpressionMinimum);
    CCExpressionEvaluatorRegister("max", CCMathExpressionMaximum);
    CCExpressionEvaluatorRegister("random", CCMathExpressionRandom);
    CCExpressionEvaluatorRegister("game", CCProjectExpressionGame);
}
