#define Sys10WriteJ_CompJ *((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->components, ((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->entities
#define Sys11ReadAWithArchTag_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys11ReadAWithArchTag_ArchTag ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 1)], ECS_ARCHETYPE_VAR->entities
#define Sys12ReadLocalHLocalDuplicateB_WriteDuplicateA_DuplicateA *((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->components, ((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->entities
#define Sys13ReadDestroyMeTag_DestroyMeTag *((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->components, ((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->entities
#define Sys14ReadA_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys1ReadA_WriteB_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys1ReadA_WriteB_CompB ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 1)], ECS_ARCHETYPE_VAR->entities
#define Sys2ReadAC_WriteB_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys2ReadAC_WriteB_CompB ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 1)], ECS_ARCHETYPE_VAR->entities
#define Sys2ReadAC_WriteB_CompC ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 2)], ECS_ARCHETYPE_VAR->entities
#define Sys3ReadAC_WriteD_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys3ReadAC_WriteD_CompC ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 1)], ECS_ARCHETYPE_VAR->entities
#define Sys3ReadAC_WriteD_CompD ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 2)], ECS_ARCHETYPE_VAR->entities
#define Sys4ReadA_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys5ReadC_CompC ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys6ReadAC_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys6ReadAC_CompC ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 1)], ECS_ARCHETYPE_VAR->entities
#define Sys7WriteB_CompB ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys8ReadD_WriteC_CompC ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys8ReadD_WriteC_CompD ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 1)], ECS_ARCHETYPE_VAR->entities
#define Sys9ReadFGH_WriteAI_CompA ECS_ARCHETYPE_VAR->components[*(ECS_ARCHETYPE_COMPONENT_INDEXES_VAR + 0)], ECS_ARCHETYPE_VAR->entities
#define Sys9ReadFGH_WriteAI_CompF *((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->components, ((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[0]))->entities
#define Sys9ReadFGH_WriteAI_CompG *((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[1]))->components, ((ECSPackedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[1]))->entities
#define Sys9ReadFGH_WriteAI_CompH *(ECSIndexedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[2]), NULL
#define Sys9ReadFGH_WriteAI_CompI *(ECSIndexedComponent*)((void*)ECS_CONTEXT_VAR + ECS_COMPONENT_OFFSETS_VAR[3]), NULL

#define ECS_ITER_TYPE_CompA CompA ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompA 0
#define ECS_ITER_DECLARE_CompA CompA ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompA ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompA COMP_A
#define ECS_ITER_TYPE_CompB CompB ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompB 0
#define ECS_ITER_DECLARE_CompB CompB ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompB ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompB COMP_B
#define ECS_ITER_TYPE_CompC CompC ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompC 0
#define ECS_ITER_DECLARE_CompC CompC ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompC ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompC COMP_C
#define ECS_ITER_TYPE_CompD CompD ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompD 0
#define ECS_ITER_DECLARE_CompD CompD ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompD ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompD COMP_D
#define ECS_ITER_TYPE_ArchTag ArchTag ECS_ITER_IGNORE(
#define ECS_ITER_KIND_ArchTag 0
#define ECS_ITER_DECLARE_ArchTag ArchTag ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_ArchTag ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_ArchTag ARCH_TAG
#define ECS_ITER_TYPE_CompF CompF ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompF 1
#define ECS_ITER_DECLARE_CompF CompF ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompF ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompF COMP_F
#define ECS_ITER_TYPE_DestroyMeTag DestroyMeTag ECS_ITER_IGNORE(
#define ECS_ITER_KIND_DestroyMeTag 1
#define ECS_ITER_DECLARE_DestroyMeTag DestroyMeTag ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_DestroyMeTag ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_DestroyMeTag DESTROY_ME_TAG
#define ECS_ITER_TYPE_CompJ CompJ ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompJ 1
#define ECS_ITER_DECLARE_CompJ CompJ ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompJ ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompJ COMP_J
#define ECS_ITER_TYPE_DuplicateA DuplicateA ECS_ITER_IGNORE(
#define ECS_ITER_KIND_DuplicateA 1
#define ECS_ITER_DECLARE_DuplicateA ECS_ITER_DECLARE_ARRAY_VAR(
#define ECS_ITER_DECLARE_ELEMENT_DuplicateA DuplicateA ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_DECLARE_ELEMENT_INDEX_DuplicateA ECS_ITER_DECLARE_ASSIGN(ECS_ITER_PREPEND(ECS_ITER_DUPLICATE_ARRAY_INDEX_SUFFIX,
#define ECS_ITER_NESTED_DuplicateA ECS_ITER_NESTED_ARRAY_ITERATOR ECS_ITER_IGNORE(
#define ECS_ID_DuplicateA DUPLICATE_A
#define ECS_ITER_TYPE_CompG CompG ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompG 1
#define ECS_ITER_DECLARE_CompG CompG ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompG ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompG COMP_G
#define ECS_ITER_TYPE_CompH CompH ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompH 2
#define ECS_ITER_DECLARE_CompH CompH ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompH ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompH COMP_H
#define ECS_ITER_TYPE_CompI CompI ECS_ITER_IGNORE(
#define ECS_ITER_KIND_CompI 2
#define ECS_ITER_DECLARE_CompI CompI ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_CompI ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_CompI COMP_I
#define ECS_ITER_TYPE_LocalDuplicateB LocalDuplicateB ECS_ITER_IGNORE(
#define ECS_ITER_KIND_LocalDuplicateB 3
#define ECS_ITER_DECLARE_LocalDuplicateB ECS_ITER_DECLARE_ARRAY_VAR(
#define ECS_ITER_DECLARE_ELEMENT_LocalDuplicateB LocalDuplicateB ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_DECLARE_ELEMENT_INDEX_LocalDuplicateB ECS_ITER_DECLARE_ASSIGN(ECS_ITER_PREPEND(ECS_ITER_DUPLICATE_ARRAY_INDEX_SUFFIX,
#define ECS_ITER_NESTED_LocalDuplicateB ECS_ITER_NESTED_ARRAY_ITERATOR ECS_ITER_IGNORE(
#define ECS_ID_LocalDuplicateB LOCAL_DUPLICATE_B
#define ECS_ITER_TYPE_LocalH LocalH ECS_ITER_IGNORE(
#define ECS_ITER_KIND_LocalH 3
#define ECS_ITER_DECLARE_LocalH LocalH ECS_ITER_DECLARE_ASSIGN(
#define ECS_ITER_NESTED_LocalH ECS_ITER_NESTED_NONE ECS_ITER_IGNORE(
#define ECS_ID_LocalH LOCAL_H

