//This file is automatically generated, modifications will be lost!
#ifndef CommonGameKit_ECSConfig_h
#define CommonGameKit_ECSConfig_h

#include <CommonGameKit/Base.h>

#ifndef ECS_ARCHETYPE_COMPONENT_MAX
#define ECS_ARCHETYPE_COMPONENT_MAX 20
#endif

#define ECS_ARCHETYPE_ENCODE_0(x) ((x) / 1)
#define ECS_ARCHETYPE_ENCODE_1(x) (((x) - 1) / 1 * (x) / 2)
#define ECS_ARCHETYPE_ENCODE_2(x) (((x) - 2) / 1 * ((x) - 1) / 2 * (x) / 3)
#define ECS_ARCHETYPE_ENCODE_3(x) (((x) - 3) / 1 * ((x) - 2) / 2 * ((x) - 1) / 3 * (x) / 4)
#define ECS_ARCHETYPE_ENCODE_4(x) (((x) - 4) / 1 * ((x) - 3) / 2 * ((x) - 2) / 3 * ((x) - 1) / 4 * (x) / 5)
#define ECS_ARCHETYPE_ENCODE_5(x) (((x) - 5) / 1 * ((x) - 4) / 2 * ((x) - 3) / 3 * ((x) - 2) / 4 * ((x) - 1) / 5 * (x) / 6)
#define ECS_ARCHETYPE_ENCODE_6(x) (((x) - 6) / 1 * ((x) - 5) / 2 * ((x) - 4) / 3 * ((x) - 3) / 4 * ((x) - 2) / 5 * ((x) - 1) / 6 * (x) / 7)
#define ECS_ARCHETYPE_ENCODE_7(x) (((x) - 7) / 1 * ((x) - 6) / 2 * ((x) - 5) / 3 * ((x) - 4) / 4 * ((x) - 3) / 5 * ((x) - 2) / 6 * ((x) - 1) / 7 * (x) / 8)
#define ECS_ARCHETYPE_ENCODE_8(x) (((x) - 8) / 1 * ((x) - 7) / 2 * ((x) - 6) / 3 * ((x) - 5) / 4 * ((x) - 4) / 5 * ((x) - 3) / 6 * ((x) - 2) / 7 * ((x) - 1) / 8 * (x) / 9)
#define ECS_ARCHETYPE_ENCODE_9(x) (((x) - 9) / 1 * ((x) - 8) / 2 * ((x) - 7) / 3 * ((x) - 6) / 4 * ((x) - 5) / 5 * ((x) - 4) / 6 * ((x) - 3) / 7 * ((x) - 2) / 8 * ((x) - 1) / 9 * (x) / 10)
#define ECS_ARCHETYPE_ENCODE_10(x) (((x) - 10) / 1 * ((x) - 9) / 2 * ((x) - 8) / 3 * ((x) - 7) / 4 * ((x) - 6) / 5 * ((x) - 5) / 6 * ((x) - 4) / 7 * ((x) - 3) / 8 * ((x) - 2) / 9 * ((x) - 1) / 10 * (x) / 11)
#define ECS_ARCHETYPE_ENCODE_11(x) (((x) - 11) / 1 * ((x) - 10) / 2 * ((x) - 9) / 3 * ((x) - 8) / 4 * ((x) - 7) / 5 * ((x) - 6) / 6 * ((x) - 5) / 7 * ((x) - 4) / 8 * ((x) - 3) / 9 * ((x) - 2) / 10 * ((x) - 1) / 11 * (x) / 12)
#define ECS_ARCHETYPE_ENCODE_12(x) (((x) - 12) / 1 * ((x) - 11) / 2 * ((x) - 10) / 3 * ((x) - 9) / 4 * ((x) - 8) / 5 * ((x) - 7) / 6 * ((x) - 6) / 7 * ((x) - 5) / 8 * ((x) - 4) / 9 * ((x) - 3) / 10 * ((x) - 2) / 11 * ((x) - 1) / 12 * (x) / 13)
#define ECS_ARCHETYPE_ENCODE_13(x) (((x) - 13) / 1 * ((x) - 12) / 2 * ((x) - 11) / 3 * ((x) - 10) / 4 * ((x) - 9) / 5 * ((x) - 8) / 6 * ((x) - 7) / 7 * ((x) - 6) / 8 * ((x) - 5) / 9 * ((x) - 4) / 10 * ((x) - 3) / 11 * ((x) - 2) / 12 * ((x) - 1) / 13 * (x) / 14)
#define ECS_ARCHETYPE_ENCODE_14(x) (((x) - 14) / 1 * ((x) - 13) / 2 * ((x) - 12) / 3 * ((x) - 11) / 4 * ((x) - 10) / 5 * ((x) - 9) / 6 * ((x) - 8) / 7 * ((x) - 7) / 8 * ((x) - 6) / 9 * ((x) - 5) / 10 * ((x) - 4) / 11 * ((x) - 3) / 12 * ((x) - 2) / 13 * ((x) - 1) / 14 * (x) / 15)
#define ECS_ARCHETYPE_ENCODE_15(x) (((x) - 15) / 1 * ((x) - 14) / 2 * ((x) - 13) / 3 * ((x) - 12) / 4 * ((x) - 11) / 5 * ((x) - 10) / 6 * ((x) - 9) / 7 * ((x) - 8) / 8 * ((x) - 7) / 9 * ((x) - 6) / 10 * ((x) - 5) / 11 * ((x) - 4) / 12 * ((x) - 3) / 13 * ((x) - 2) / 14 * ((x) - 1) / 15 * (x) / 16)
#define ECS_ARCHETYPE_ENCODE_16(x) (((x) - 16) / 1 * ((x) - 15) / 2 * ((x) - 14) / 3 * ((x) - 13) / 4 * ((x) - 12) / 5 * ((x) - 11) / 6 * ((x) - 10) / 7 * ((x) - 9) / 8 * ((x) - 8) / 9 * ((x) - 7) / 10 * ((x) - 6) / 11 * ((x) - 5) / 12 * ((x) - 4) / 13 * ((x) - 3) / 14 * ((x) - 2) / 15 * ((x) - 1) / 16 * (x) / 17)
#define ECS_ARCHETYPE_ENCODE_17(x) (((x) - 17) / 1 * ((x) - 16) / 2 * ((x) - 15) / 3 * ((x) - 14) / 4 * ((x) - 13) / 5 * ((x) - 12) / 6 * ((x) - 11) / 7 * ((x) - 10) / 8 * ((x) - 9) / 9 * ((x) - 8) / 10 * ((x) - 7) / 11 * ((x) - 6) / 12 * ((x) - 5) / 13 * ((x) - 4) / 14 * ((x) - 3) / 15 * ((x) - 2) / 16 * ((x) - 1) / 17 * (x) / 18)
#define ECS_ARCHETYPE_ENCODE_18(x) (((x) - 18) / 1 * ((x) - 17) / 2 * ((x) - 16) / 3 * ((x) - 15) / 4 * ((x) - 14) / 5 * ((x) - 13) / 6 * ((x) - 12) / 7 * ((x) - 11) / 8 * ((x) - 10) / 9 * ((x) - 9) / 10 * ((x) - 8) / 11 * ((x) - 7) / 12 * ((x) - 6) / 13 * ((x) - 5) / 14 * ((x) - 4) / 15 * ((x) - 3) / 16 * ((x) - 2) / 17 * ((x) - 1) / 18 * (x) / 19)
#define ECS_ARCHETYPE_ENCODE_19(x) (((x) - 19) / 1 * ((x) - 18) / 2 * ((x) - 17) / 3 * ((x) - 16) / 4 * ((x) - 15) / 5 * ((x) - 14) / 6 * ((x) - 13) / 7 * ((x) - 12) / 8 * ((x) - 11) / 9 * ((x) - 10) / 10 * ((x) - 9) / 11 * ((x) - 8) / 12 * ((x) - 7) / 13 * ((x) - 6) / 14 * ((x) - 5) / 15 * ((x) - 4) / 16 * ((x) - 3) / 17 * ((x) - 2) / 18 * ((x) - 1) / 19 * (x) / 20)
#define ECS_ARCHETYPE_ENCODE_20(x) (((x) - 20) / 1 * ((x) - 19) / 2 * ((x) - 18) / 3 * ((x) - 17) / 4 * ((x) - 16) / 5 * ((x) - 15) / 6 * ((x) - 14) / 7 * ((x) - 13) / 8 * ((x) - 12) / 9 * ((x) - 11) / 10 * ((x) - 10) / 11 * ((x) - 9) / 12 * ((x) - 8) / 13 * ((x) - 7) / 14 * ((x) - 6) / 15 * ((x) - 5) / 16 * ((x) - 4) / 17 * ((x) - 3) / 18 * ((x) - 2) / 19 * ((x) - 1) / 20 * (x) / 21)

#define ECS_ARCHETYPE_ENCODE_COMBINE(a, b) (a) + (b)

#define ECS_ARCHETYPE0_INDEX 0
#define ECS_ARCHETYPE1_INDEX(x0) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_0(x0), ECS_ARCHETYPE0_INDEX)
#define ECS_ARCHETYPE2_INDEX(x0, x1) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_1(x1), ECS_ARCHETYPE1_INDEX(x0))
#define ECS_ARCHETYPE3_INDEX(x0, x1, x2) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_2(x2), ECS_ARCHETYPE2_INDEX(x0, x1))
#define ECS_ARCHETYPE4_INDEX(x0, x1, x2, x3) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_3(x3), ECS_ARCHETYPE3_INDEX(x0, x1, x2))
#define ECS_ARCHETYPE5_INDEX(x0, x1, x2, x3, x4) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_4(x4), ECS_ARCHETYPE4_INDEX(x0, x1, x2, x3))
#define ECS_ARCHETYPE6_INDEX(x0, x1, x2, x3, x4, x5) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_5(x5), ECS_ARCHETYPE5_INDEX(x0, x1, x2, x3, x4))
#define ECS_ARCHETYPE7_INDEX(x0, x1, x2, x3, x4, x5, x6) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_6(x6), ECS_ARCHETYPE6_INDEX(x0, x1, x2, x3, x4, x5))
#define ECS_ARCHETYPE8_INDEX(x0, x1, x2, x3, x4, x5, x6, x7) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_7(x7), ECS_ARCHETYPE7_INDEX(x0, x1, x2, x3, x4, x5, x6))
#define ECS_ARCHETYPE9_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_8(x8), ECS_ARCHETYPE8_INDEX(x0, x1, x2, x3, x4, x5, x6, x7))
#define ECS_ARCHETYPE10_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_9(x9), ECS_ARCHETYPE9_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8))
#define ECS_ARCHETYPE11_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_10(x10), ECS_ARCHETYPE10_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9))
#define ECS_ARCHETYPE12_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_11(x11), ECS_ARCHETYPE11_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10))
#define ECS_ARCHETYPE13_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_12(x12), ECS_ARCHETYPE12_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11))
#define ECS_ARCHETYPE14_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_13(x13), ECS_ARCHETYPE13_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12))
#define ECS_ARCHETYPE15_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_14(x14), ECS_ARCHETYPE14_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13))
#define ECS_ARCHETYPE16_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_15(x15), ECS_ARCHETYPE15_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14))
#define ECS_ARCHETYPE17_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_16(x16), ECS_ARCHETYPE16_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15))
#define ECS_ARCHETYPE18_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_17(x17), ECS_ARCHETYPE17_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16))
#define ECS_ARCHETYPE19_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_18(x18), ECS_ARCHETYPE18_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17))
#define ECS_ARCHETYPE20_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19) ECS_ARCHETYPE_ENCODE_COMBINE(ECS_ARCHETYPE_ENCODE_19(x19), ECS_ARCHETYPE19_INDEX(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18))

#ifndef ECS_COMPONENT_ARCHETYPE1_MAX
#define ECS_COMPONENT_ARCHETYPE1_MAX ECS_ARCHETYPE_ENCODE_0(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE2_MAX
#define ECS_COMPONENT_ARCHETYPE2_MAX ECS_ARCHETYPE_ENCODE_1(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE3_MAX
#define ECS_COMPONENT_ARCHETYPE3_MAX ECS_ARCHETYPE_ENCODE_2(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE4_MAX
#define ECS_COMPONENT_ARCHETYPE4_MAX ECS_ARCHETYPE_ENCODE_3(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE5_MAX
#define ECS_COMPONENT_ARCHETYPE5_MAX ECS_ARCHETYPE_ENCODE_4(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE6_MAX
#define ECS_COMPONENT_ARCHETYPE6_MAX ECS_ARCHETYPE_ENCODE_5(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE7_MAX
#define ECS_COMPONENT_ARCHETYPE7_MAX ECS_ARCHETYPE_ENCODE_6(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE8_MAX
#define ECS_COMPONENT_ARCHETYPE8_MAX ECS_ARCHETYPE_ENCODE_7(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE9_MAX
#define ECS_COMPONENT_ARCHETYPE9_MAX ECS_ARCHETYPE_ENCODE_8(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE10_MAX
#define ECS_COMPONENT_ARCHETYPE10_MAX ECS_ARCHETYPE_ENCODE_9(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE11_MAX
#define ECS_COMPONENT_ARCHETYPE11_MAX ECS_ARCHETYPE_ENCODE_10(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE12_MAX
#define ECS_COMPONENT_ARCHETYPE12_MAX ECS_ARCHETYPE_ENCODE_11(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE13_MAX
#define ECS_COMPONENT_ARCHETYPE13_MAX ECS_ARCHETYPE_ENCODE_12(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE14_MAX
#define ECS_COMPONENT_ARCHETYPE14_MAX ECS_ARCHETYPE_ENCODE_13(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE15_MAX
#define ECS_COMPONENT_ARCHETYPE15_MAX ECS_ARCHETYPE_ENCODE_14(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE16_MAX
#define ECS_COMPONENT_ARCHETYPE16_MAX ECS_ARCHETYPE_ENCODE_15(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE17_MAX
#define ECS_COMPONENT_ARCHETYPE17_MAX ECS_ARCHETYPE_ENCODE_16(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE18_MAX
#define ECS_COMPONENT_ARCHETYPE18_MAX ECS_ARCHETYPE_ENCODE_17(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE19_MAX
#define ECS_COMPONENT_ARCHETYPE19_MAX ECS_ARCHETYPE_ENCODE_18(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_COMPONENT_ARCHETYPE20_MAX
#define ECS_COMPONENT_ARCHETYPE20_MAX ECS_ARCHETYPE_ENCODE_19(ECS_ARCHETYPE_COMPONENT_MAX)
#endif

#ifndef ECS_ARCHETYPE_MAX
#define ECS_ARCHETYPE_MAX ECS_ARCHETYPE_COMPONENT_MAX
#elif ECS_ARCHETYPE_MAX > 20
#error ECS_ARCHETYPE_MAX exceeds maximum limit. Regenerate config to support required size.
#endif

#ifndef ECS_PACKED_COMPONENT_MAX
#define ECS_PACKED_COMPONENT_MAX 64
#endif

#ifndef ECS_INDEXED_COMPONENT_MAX
#define ECS_INDEXED_COMPONENT_MAX 64
#endif

#ifndef ECS_LOCAL_COMPONENT_MAX
#define ECS_LOCAL_COMPONENT_MAX 64
#endif

#define ECS_COMPONENT_MAX (ECS_ARCHETYPE_COMPONENT_MAX + ECS_PACKED_COMPONENT_MAX + ECS_INDEXED_COMPONENT_MAX + ECS_LOCAL_COMPONENT_MAX)

#endif
