//This file is automatically generated, modifications will be lost!
#define CC_CONTAINER_DECLARE_PRESET_CCArray \
CC_CONTAINER_DECLARE(CCArray, CCChar); \
CC_CONTAINER_DECLARE(CCArray, CCExpressionEvaluator); \
CC_CONTAINER_DECLARE(CCArray, CCFontGlyph); \
CC_CONTAINER_DECLARE(CCArray, GLint); \
CC_CONTAINER_DECLARE(CCArray, uint32_t);

#define CC_CONTAINER_DECLARE_PRESET_CCCollection \
CC_CONTAINER_DECLARE(CCCollection, CCCollection(CCTextAttribute)); \
CC_CONTAINER_DECLARE(CCCollection, CCCollectionEntry); \
CC_CONTAINER_DECLARE(CCCollection, CCComponent); \
CC_CONTAINER_DECLARE(CCCollection, CCEntity); \
CC_CONTAINER_DECLARE(CCCollection, CCExpression); \
CC_CONTAINER_DECLARE(CCCollection, CCString); \
CC_CONTAINER_DECLARE(CCCollection, CCTextAttribute); \
CC_CONTAINER_DECLARE(CCCollection, CCTextDrawable); \
CC_CONTAINER_DECLARE(CCCollection, FSPath); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInput); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInputBuffer); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInputTexture); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInputVertexBuffer); \
CC_CONTAINER_DECLARE(CCCollection, GUIObject);

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentIndexMap \
CC_CONTAINER_DECLARE(CCConcurrentIndexMap, CCComponent);

#define CC_CONTAINER_DECLARE_PRESET_CCDictionary \
CC_CONTAINER_DECLARE(CCDictionary, CCComponent, size_t); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, CCAnimationInterpolator); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, CCInputMapComponentCallback); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, CCKeyboardKeycode); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, CFTypeRef); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, GLShaderAttributeInfo); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, GLShaderLibrarySource); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, GLShaderUniformInfo); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, size_t);

#define CC_CONTAINER_DECLARE_PRESET_CCLinkedList \
CC_CONTAINER_DECLARE(CCLinkedList, CCArray);

#define CC_CONTAINER_DECLARE_PRESET_CCList \
CC_CONTAINER_DECLARE(CCList, uint64_t);

#define CC_CONTAINER_DECLARE_PRESET_CCOrderedCollection \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCComponent); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCExpression); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCOrderedCollection(CCTextAttribute)); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCString); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCTextAttribute); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCTextDrawable); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPath); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPathComponent); \
CC_CONTAINER_DECLARE(CCOrderedCollection, GUIObject); \
CC_CONTAINER_DECLARE(CCOrderedCollection, _Bool); \
CC_CONTAINER_DECLARE(CCOrderedCollection, double); \
CC_CONTAINER_DECLARE(CCOrderedCollection, float);

#define CC_CONTAINER_DECLARE_PRESET_CCQueue \
CC_CONTAINER_DECLARE(CCQueue, size_t);
